### ISSUE TITLE
Unable to overcome max-width limit of #write div

### ISSUE THREAD

**Issue by mmatti** [typora/typora-issues#1]
Typora locks #write to 854px, and applying a custom stylesheet (even with the "!important" cheat) can't override it. Trying to get line widths to flow and wrap at the window's edge, instead of a fixed position.

None of the supplied themes support full width line reflow, which is fine, but the inability to override with a custom theme is frustrating.

**Comment by Fastidious** [comment]
I second this. Not really want it to wrap at the exact edge (50 pixels or so from it is fine, you know, like a regular word processor [but better, or course, it is Markdown).

**Comment by abnerlee** [comment]
Hi, I've tried with typora, but I found currently, the max-width can be override.

For example, in your custom stylesheet:

``` css
#write {
    max-width: initial; // this will remove the default max-width
    margin: 0 auto;
    padding: 0 0 0 0; // this will define the pixels between writing area to window's edge
}
```

Then the writing area will be expanded to the edge
