### ISSUE TITLE
Can you support vertical setting of types for CJK？能支持竖排吗？

### ISSUE THREAD

**Issue by iblueer** [typora/typora-issues#1121]
希望可以在typora上体验到传统文化的魅力。
I hope people can experience the charming point of traditional East Asian Culture.

Just like--this.
<img width="708" alt="2017-12-24 12 25 10" src="https://user-images.githubusercontent.com/3581944/34324228-8a2a7612-e8a5-11e7-9520-e4799f20f9c2.png">

**Comment by abnerlee** [comment]
It is possible. But code fences and math can not support this perfectly

How-to:

Follow http://support.typora.io/Add-Custom-CSS/

And add custom css:
```
#write {
 writing-mode: vertical-rl;
-webkit-writing-mode: vertical-rl;
}
```

**Comment by iblueer** [comment]
Thank you for teaching me.

But one more question:

 I found that before the first sentence, there is a stable space like this. How should I delete it?

<img width="182" alt="2017-12-31 1 03 22" src="https://user-images.githubusercontent.com/3581944/34455998-96afdf0a-edc6-11e7-9984-a559a4acd80e.png">

**Comment by iblueer** [comment]
And I found that quotation marks I deleted still show on screen.

This must be kind of bug, right?

<img width="50" alt="2017-12-31 1 13 56" src="https://user-images.githubusercontent.com/3581944/34456042-173ceb80-edc8-11e7-9ecf-c5202a3e5ea0.png">

**Comment by abnerlee** [comment]
> I found that before the first sentence, there is a stable space like this. How should I delete it?

There should be other modification for supporting vertical writing mode.

```css
#write > p:first-child, #write > ul:first-child, #write > ol:first-child, #write > pre:first-child, #write > blockquote:first-child, #write > div:first-child, #write > table:first-child {
    margin-top: 0;
}
```
