### ISSUE TITLE
Not possible to style checked task list items

### ISSUE THREAD

**Issue by joakimc** [typora/typora-issues#1237]
I'm trying to style checked task list items, and according to the documentation this should work:

```css
.task-list-item input:checked {
  text-decoration: line-through;
}
```
I'm currently editing in github.user.css, and I'm able to style other elements, but not checked task list items.
