### ISSUE TITLE
re-regression: Default filename logic fails in the presence of YAML front matter

### ISSUE THREAD

**Issue by Narno** [typora/typora-issues#1255]
Hello, I got the same problem as #952 with Typora Version 0.9.9.12.5 (Mac OSX).

When I try to save a document with that content, the default filename is `Sans titre.md` (french words for "Untitled"):
```yaml
---
title: Test
date: 2018-02-21
---

# Test

```

I loved this feature, I miss her a lot! <3
