### ISSUE TITLE
Image align doesn't work 0.946

### ISSUE THREAD

**Issue by jacquen** [typora/typora-issues#1307]
Hi, Team
after upgrade 0.946, the image align doesn't work as before, I use below customize css to align picture to left before, but now it doesn't work any more, it always appear in center now. Any idea?

===========================CSS code======
p .md-image:only-child{
    width: auto;
    text-align: inherit;
}

**Comment by abnerlee** [comment]
you could just use `text-align: inherit !important;`

or 
```css
.md-line .md-image:only-child{
    display: inline-block;
    width: 100%;
    text-align: left;
}
```
