### ISSUE TITLE
Inline code in source code mode is using comment css instead of code css

### ISSUE THREAD

**Issue by vr8hub** [typora/typora-issues#1362]
Typora .9.9.13.6 on OSX 10.12.6.

When in source code mode, e.g. \`something like this\`, Typora is using the .cm-comment CSS instead of the .cm-code CSS.

Here is an excerpt of the two lines I have in my theme (the variables are defined at the top of the theme):
```css
.cm-s-typora-default .cm-code { color: var(--sol-magenta); }
.cm-s-typora-default .cm-comment { color: var(--sol-green); font-style:italic; }
```

Inline code in source code mode is displaying in green rather in magenta. I confirmed that this was the issue by changing the color of .cm-comment to red; the inline code then started displaying in red.
