### ISSUE TITLE
[Solarized theme] Code blocks have extra whitespace below them until they're highlighted.

### ISSUE THREAD

**Issue by vr8hub** [typora/typora-issues#1363]
Typora .9.9.13.6 on OSX 10.12.6.

When switching to my theme (a hacked version of Solarized), this is the display of a code block. Notice the apparent extra blank line below the only line in the code block.
![unselected](https://user-images.githubusercontent.com/19378955/38071366-7bacf96c-32e6-11e8-9ed4-03ddac2d38cb.jpg)

If I click in that code block and do nothing but just highlight part of the line, that blank line disappears, as you can see here.
![selected](https://user-images.githubusercontent.com/19378955/38071365-7b95cbde-32e6-11e8-8273-37d01154b912.jpg)

The block should display as it does in the second case (without the apparent blank line) all the time.

This is consistent; it happens every time I switch to another theme and switch back to mine. (The other themes, e.g. Academic, never show that blank line.)

Just for completeness, here's the pertinent section of the CSS:
```css
pre.md-fences {
    padding: 10px 10px;
    margin-bottom: 10px;
}

.md-fences {
    font-family: 'Latin Modern Mono Light', "Latin Modern Mono", monospace !important;
    font-size: 0.9em;
    color: var(--sol-orange);
    background-color: var(--darker-bg-color);
}
```
