### ISSUE TITLE
Applying font to a unicode range.

### ISSUE THREAD

**Issue by rp-karanth** [typora/typora-issues#1373]
In Atom Editor unicode-range can be used to apply fonts to certain codeponts. But Typora is not allowing that feature.

**Code used in Atom Editor**  
```css
@font-face{
    font-family: "Annapurna SIL";
    src: local('C:\Windows\Fonts\AnnapurnaSIL-R.otf');
    unicode-range: U+0900-A8FB;
}
.editor{
    font-family: 'DejaVu Sans Mono', "Annapurna SIL";}
```

The code I am adding to whitey.css is this: 
```css
@font-face{
    font-family: "Annapurna SIL";
    src: local('C:\Windows\Fonts\AnnapurnaSIL-R.otf');
    unicode-range: U+0900-A8FB;
}
body {
	font-family: "Vollkorn", "Annapurna SIL", Palatino, Times;
	color: #333;
	line-height: 1.4;
	text-align: justify;
}
```

Is this a bug or am I doing something wrong.

**Comment by abnerlee** [comment]
For your CSS, first font `Vollkorn` will be used, if "Vollkorn" does not exists, it will fallback to "Annapurna SIL".

So, maybe it should be 
```css
body {
	font-family:  "Annapurna SIL", Palatino, Times;
	color: #333;
	line-height: 1.4;
	text-align: justify;
}
```
FYI
Typora for macOS is based on Webkit/Safari.
Typora for Linux/Windows is based on Chrome.

So if the css work for Safari/Chrome, it will also work for Typora. You could debug css by enable "debug mode" in help menu or preference panel, then pop up DevTools from context menu.
