### ISSUE TITLE
page margins in pdf export

### ISSUE THREAD

**Issue by timrosskamp** [typora/typora-issues#1479]
I tried to decrease the margins around a page on the pdf export:
```css
@media print {
    @page {
        margin: 10mm;
    }
}
```

This only works on the top and the bottom margin. The margin left and right gets added up to the default distance. With the code above in my theme, the distance from the text to the left side of the page is accually larger than the default distance.
