### ISSUE TITLE
Margins when printing

### ISSUE THREAD

**Issue by lukejanicke** [typora/typora-issues#1519]
I cannot seem to gain full control over margins when exporting to PDF/printing. With `margin: 0;` on everything there is still some margin in PDF/print and it’s different between top/bottom and left/right.

The following CSS gives me ~2 cm margins.

```CSS
@media print {
    html {
        font-size: 16px!important;
        padding: 0 !important;
        margin: 0 !important;
    }
    body.typora-export {
        padding: 0 !important;
        margin: 0 !important;
    }
    .typora-export #write {
        padding: 0 !important;
        margin-top: 4mm !important;
        margin-right: 15mm !important;
        margin-bottom: 4mm !important;
        margin-left: 15mm !important;
    }
}
```

Is there some other CSS that I am not aware of?

I’ve searched the Typora core CSS files and couldn’t see anything else that adds margins.
