### ISSUE TITLE
How to reduce the size of diagram? 

### ISSUE THREAD

**Issue by bescks** [typora/typora-issues#1568]
For example, produced by library mermaid. Sometimes, diagram takes too much space in file.

**Comment by abnerlee** [comment]
It can be configured by CSS, following https://support.typora.io/Add-Custom-CSS/

```
.md-diagram-panel-preview {
    zoom: 50%; 
}
```

or 

```
.md-diagram-panel-preview svg{
   max-width: 400px;
}
```

**Comment by AhmedThahir** [comment]
I want to enlarge my diagrams.

``` css
.md-diagram-panel-preview {
    zoom: 200%; 
}
```
works perfectly in windows typora
does not work in macos.

Kindly help me out

**Comment by YunfangHou** [comment]
> It can be configured by CSS, following https://support.typora.io/Add-Custom-CSS/
> 
> ```
> .md-diagram-panel-preview {
>     zoom: 50%; 
> }
> ```
> 
> or
> 
> ```
> .md-diagram-panel-preview svg{
>    max-width: 400px;
> }
> ```

Hi. It works for the view in Typora, but the diagram still seems large when exported as a PDF. Is there any way to apply this change when exporting PDF?

**Comment by adrian-livefront** [comment]
@YunfangHou this worked for me for PDF export with `sequenceDiagram`:

```css
.md-diagram-panel svg{
   height: auto;
   zoom: 100%;
   max-width: 600px;
 }
```
