### ISSUE TITLE
Support for inline footnotes in live preview

### ISSUE THREAD

**Issue by GandalfSaxe** [typora/typora-issues#1571]
Support of inline footnotes would be a very welcome addition.

## Example of ordinary/inline footnotes
1. Source markdown:
```markdown
Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.


Here is an inline note.^[Inlines notes are easier to write, since
you don't have to pick an identifier and move down to type the
note.]
```

2. Typora live preview:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/12127864/41719855-93c9843a-7561-11e8-91fe-e610a49c37fc.png">

3. The result of inline footnotes is the same when converted to .tex:
```latex
Here is a footnote reference,\footnote{Here is the footnote.} and
another.\footnote{Here's one with multiple blocks.}

Here is an inline note.\footnote{Inlines notes are easier to write,
  since you don't have to pick an identifier and move down to type the
  note.}
```

4. ..and also the same as pdf:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/12127864/41719959-db238bd2-7561-11e8-868a-e95498221d45.png">

So inline footnotes are simply more convenient to use in situations where the output is intended to be LaTeX or PDF. Would be great if they could be rendered in superscript similar to ordinary footnotes.

**Comment by swelet** [comment]
I agree. This would make a great improvement compared to old school markdown footnotes.

**Comment by abnerlee** [comment]
merge into #2448

**Comment by abnerlee** [comment]
relates #912

**Comment by jcarpenter** [comment]
Huge +1 for this. I use inline footnotes heavily, and would *love* if they collapsed into the same excellent "footnote hover button" UI that non-inline footnotes get.

**Comment by jcarpenter** [comment]
In the meantime I rolled my own solution by styling `mark` tags. 
![references-workflow-1](https://user-images.githubusercontent.com/1425497/68905095-da270a80-06f4-11ea-88fb-67ca0b09c0a0.gif)

**Comment by DutchPete** [comment]
@jcarpenter : I use footnotes a lot too. I don't get how @GandalfSaxe would work/be rendered, but I'll wait for @abnerlee's reply/solution.

Meanwhile, I am interested in your workaround, but cannot follow your lightening-fast GIF. Could you expand on those styling `mark` tags and how to get those footnotes or `fn` tags? How does it translate into a footnote? Or does it translate into an inline note?

I apologise for being dense and asking what are perhaps a silly questions.

**Comment by jcarpenter** [comment]
@DutchPete . Good questions! Yep, they translate into real inline footnotes eventually. It's a bit convoluted. The details:

### When editing in Typora, whenever I want an inline footnote, I use a `==...==` mark tag instead.

I use mark tags because 1) most importantly, Typora recognizes them, and therefore gives us the hooks to style them, and 2) I don't need actual marks in my workflow, so I'm free to use the element for something else. First I have to enable support for mark tags in Preferences > Markdown > Highlight.

### I style marks with the following CSS in a [custom theme](http://theme.typora.io/doc/Write-Custom-Theme/)

This is simplified quite a bit. The actual rules have a ton of additional aesthetic-only properties.

```css
/* Mark when NOT selected */
/* Collapses to just `fn` */

mark {
    position: relative;
    cursor: text;
}

mark::before {
    font-size: 0.9em;
    content: 'fn'; /* Display an "fn" */
}

mark span {
    display: none; /* Hide the actual content */
}

/* Mark when hovered */
/* Displays contents in bubble, centered below the mark */

span:not(.md-expand) mark:hover span {
    position: absolute;
    transform: translate(-50%, 100%);
    bottom: -0.4em;
    left: 50%;
    z-index: 100;
}

/* Footnote when selected */
/* Displays editable contents inline */

.md-expand mark {
    font-size: inherit;
    padding: 0;
    margin: 0;
    background-color: rgba(0, 0, 0, 0);
    color: inherit;
    cursor: text;
}

.md-expand mark::before { content: none; }
.md-expand mark span { display: inline; }

```

### I replace marks with inline footnotes

When I'm ready to export my notes for public consumption, I run everything through a node export script. It runs a bunch of simple regex replace functions to modify image paths, inject metadata, etc. One method replaces the marks with inline footnotes, while leaving the contents intact:

```js
let post = fs.readFileSync('sealevelrise.md', 'utf8')
post = post.replace(/==\[/gm, '^[[')
post = post.replace(/\]==/gm, ']]')
```
The export script then runs the file through [node-pandoc](https://www.npmjs.com/package/node-pandoc), to replace citation keys with actual references. It then writes a new Markdown file to disk, so the original is untouched, and a Bash script finally pushes everything to a GitHub repo.

### I convert everything to HTML and publish

My static site generator setup (I use [11ty.io](https://www.11ty.io/)), pulls down the formatted files from the repo, and converts everything to HTML. The end result is seen below. I use a bunch of styles and a bit of JS to create a similar "hover footnotes" user experience. 

![hover-citations](https://user-images.githubusercontent.com/1425497/68978913-f25c5f80-07b0-11ea-80b0-445807e7499c.gif)

The site's not live yet, mind you.
