### ISSUE TITLE
how can I use the filename in yaml

### ISSUE THREAD

**Issue by Layty** [typora/typora-issues#1637]
now i want to set  
``` 
typora-root-url: ..
typora-copy-images-to: ../${filename}.assert
```
but the `${filename}` just a string and not a var,so how can I set the path to the    ../filename.assert.

**Comment by abnerlee** [comment]
`${filename}` in YAML is not suppported

**Comment by Layty** [comment]
so it means that for each file ,I have to change the YAML by myself.right?

**Comment by abnerlee** [comment]
Well, for now, we do not support variables in YAML, we will consider support it in future.

For your case, you could just use a same folder for those files, such as `asserts`. Or set `${filename}.assert` in preferences panels, but it will be applied globally.

**Comment by Chameleons18** [comment]
if use {{ title }} replace ${filename}

**Comment by Chameleons18** [comment]
If use {{ title }} replace ${filename}, it's ok. But like this is error.
```yaml
title: {{ title }}
typora-root-url: ..
typora-copy-images-to: {{'../images/post/' + title + '/'}}
```
result: More quotes
```yaml
title: this_is_title
typora-root-url: ..
typora-copy-images-to: ../images/post/"this_is_title"/
```
