### ISSUE TITLE
Let the editor scroll past end of file

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#185]
Can you please add an option to let the editor scroll past end of file? I'm always having to keep manually adding a bunch of Enters at the bottom of a file, so that I'm editing mid-screen and not at the very bottom.

E.g., TextMate has this as View > Allow/Disallow Scroll Past End menu option. Atom has this in its Preferences:

<img width="255" alt="untitled 6" src="https://cloud.githubusercontent.com/assets/1819485/15967183/9b2b8c42-2ef4-11e6-91b8-f96f7be5d55e.png">

Suggested in a [Twitter post](https://twitter.com/AlexPasternak/status/705073803542409217) earlier this year, but capturing here in the official issue list for tracking.

**Comment by smallx** [comment]
I agree with you :+1:

**Comment by MZhoume** [comment]
Would be great for this functionality to be implemented.

**Comment by disrupted** [comment]
any news regarding this?

**Comment by sagischwarz** [comment]
Came here to open an issue on the same topic and found this old one. I know that there is the typewriter mode that keeps the current line in the middle of the screen, but please consider again if you could implement this feature.

**Comment by lipengzhou** [comment]
I found a solution.
Go to `base.user.css` in the Themes directory of Typora.   
Then append the following

```css
.write {
  margin-bottom: 20em; /* The larger the number, the more space you have from the bottom */
}
```

Finally, restarting Typora takes effect.

**Comment by snail123815** [comment]
> 

Does not function now. Instead:

```css
#write {
    margin-bottom: 20em; /* The larger the number, the more space you have from the bottom */
}
```
