### ISSUE TITLE
Please add left outline folding

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#186]
When outline panel appear on the right, you can fold the lists, as below:
![2016-06-12 12 43 29](https://cloud.githubusercontent.com/assets/10832544/15989042/96f644d4-309b-11e6-9884-2be1c32a73b9.png)

But it seems I can not fold list when appear on the left:
![2016-06-12 12 43 43](https://cloud.githubusercontent.com/assets/10832544/15989043/aa08e0cc-309b-11e6-9af1-670bffda1712.png)

Please make it also can, thanks.

regards,

**Comment by smallx** [comment]
@leewi9 你那从Word中复制一段中文段落到Typora中，段落最后会出现乱码吗？ :question:

**Comment by leewi9** [comment]
@smallx 貌似pdf和word中复制，都会出现乱码。

He's asking me whether typo shows garbled characters when pasting from Word and I reply yes.

**Comment by smallx** [comment]
Yep, it may be a bug. But not very important.

**Comment by leewi9** [comment]
@abnerlee any update?

**Comment by leewi9** [comment]
@abnerlee Hi abnerlee, sorry to bother, may I  know the plan for this function, I'm really looking forward to it. I'll appreciate it very much if you could give an estimate, thank you very much.

**Comment by abnerlee** [comment]
@leewi9 since #181 is fixed, outline panel will be usable again even when there's many headings in the article. 

So folding in outline panel is not in high priority.

For hot fix, please put following CSS:

```css
.pin-outline .outline-expander {
    display: table-cell
}

.pin-outline .outline-children {
    display: none;
}

.pin-outline .outline-item-open>.outline-children {
    display: block;
}
.
```
