### ISSUE TITLE
<ol> shows through blockquotes.

### ISSUE THREAD

**Issue by lloyd094** [typora/typora-issues#1865]
![image](https://user-images.githubusercontent.com/22482891/46893320-5f225f00-ce25-11e8-8784-ec40af18cd56.png)

When extending blockquotes to the left while in a list, the bullets (or numbers) show through. Is there a way to hide them, or not show them at all if content is there?

**Comment by abnerlee** [comment]
It is defined by CSS.

```
blockquote ol {
list-style-type: none;
}
```

**Comment by lloyd094** [comment]
Perhaps this is an issue with Typora itself then? Both in program and in PDF export, it still shows up while using the option.

![image](https://user-images.githubusercontent.com/22482891/46971274-69846900-d070-11e8-8735-e3e515137cd7.png)

**Comment by abnerlee** [comment]
Do you use custom CSS, can this be reproduced using the default theme?

**Comment by lloyd094** [comment]
I reproduced it with the default theme, and have narrowed down the code that causes it. This is from my custom theme (for law notes), as I'm trying to emulate a style used by other books. Here's what it looks like under default:
![image](https://user-images.githubusercontent.com/22482891/46993645-1a1c5800-d0c5-11e8-9d20-3b3778b16362.png)

The code added is:
```css
blockquote {
    border: 1px solid #a2a9b1;
    border-radius: 4px;
    box-shadow: 1px 1px 1px #ccc;
    background-color: #f3f3f3;
    padding: 5px;
    margin: 0.75em;
    position: relative;
    left: 0px;
}
blockquote ol {
    list-style-type: none;
}
li blockquote {
    margin-left: -34px;
    width: calc(100% + 44px);
}
li li blockquote {
    margin-left: -59px;
    width: calc(100% + 69px);
}
li li li blockquote {
    margin-left: -84px;
    width: calc(100% + 94px);
}
li li li li blockquote {
    margin-left: -109px;
    width: calc(100% + 119px);
}
li li li li li blockquote {
    margin-left: -134px;
    width: calc(100% + 144px);
}
li li li li li li blockquote {
    margin-left: -159px;
    width: calc(100% + 169px);
}
li li li li li li li blockquote {
    margin-left: -184px;
    width: calc(100% + 194px);
}
```

If you want to see the public version of my theme, you can find it here - the only part missing is the bit of code you suggested above: 
https://github.com/lloyd094/Typora-Law-School/blob/master/law.css

As a note, the initial file was from the academic theme (though it has changed significantly).

**Comment by abnerlee** [comment]
This is caused by your CSS:

```
li blockquote {
    margin-left: -34px;
    width: calc(100% + 44px);
}
li li blockquote {
    margin-left: -59px;
    width: calc(100% + 69px);
}
li li li blockquote {
    margin-left: -84px;
    width: calc(100% + 94px);
}
li li li li blockquote {
    margin-left: -109px;
    width: calc(100% + 119px);
}
li li li li li blockquote {
    margin-left: -134px;
    width: calc(100% + 144px);
}
li li li li li li blockquote {
    margin-left: -159px;
    width: calc(100% + 169px);
}
li li li li li li li blockquote {
    margin-left: -184px;
    width: calc(100% + 194px);
}
```

**Comment by lloyd094** [comment]
Unfortunately the z-index doesn't work - I have tried that both now, and previously. As for the `li>*:first-child`, could you point me in the right direction? I'm not sure what you're getting at.

Thanks for all the help btw.

**Comment by abnerlee** [comment]
I mean move "1.0" from `ul` to `li>:first-child`

For example 
```css
ol {
list-style-type: none;
ounter-reset: li-counter;
}

ol li {
  counter-increment: li-counter;
}

li>*:first-child {
    content: counter(my-awesome-counter) ". ";
    margin-left: -4ch;
    position: absolute;
}

li>blockquote:first-child {
  opacity: 0;
}
```
