### ISSUE TITLE
Scrollbar (and many other widgets) doesn't follow dark theme or macOS Mojave dark mode

### ISSUE THREAD

**Issue by itsuhane** [typora/typora-issues#1919]
Description:
Scrollbars are not dimmed as they should be in dark theme. Also, widgets in preferences panel is not respecting dark mode.

OS version: macOS Mojave
Typora version: 0.9.9.19.1(1301)

What's the problem: please see red boxes in screenshot.

What's expected: please see yellow boxes in screenshot.

Possible resolution:
For user themes, add a `--ui-theme-mode` property  to `:root` selector:
```css
:root {
    --ui-theme-mode: light; /* use light mode everywhere */
    --ui-theme-mode: dark; /* use dark mode everywhere */
    --ui-theme-mode: dark-theme; /* suggest using dark mode for main editor, but left others (such as preference panel) following system config */
    --ui-theme-mode: light-theme; /* suggest using light mode... */
}
```

Screenshot: ![image](https://user-images.githubusercontent.com/1052233/47715327-76ad7480-dc7a-11e8-9260-b5d010260703.png)
