### ISSUE TITLE
auto number headings

### ISSUE THREAD

**Issue by hitzhangjie** [typora/typora-issues#1940]
Hi, guys, can we auto number the outline headings?

I create a theme by adding the following lines to render headings as auto numbered, can we auto number the outline?

```css
body {
    counter-reset: h1
}

h1 {
    counter-reset: h2
}

h2 {
    counter-reset: h3
}

h3 {
    counter-reset: h4
}

h4 {
    counter-reset: h5
}

h5 {
    counter-reset: h6
}

h1:before {
    counter-increment: h1;
    content: counter(h1) ". "
}

h2:before {
    counter-increment: h2;
    content: counter(h1) "." counter(h2) ". "
}

h3:before {
    counter-increment: h3;
    content: counter(h1) "." counter(h2) "." counter(h3) ". "
}

h4:before {
    counter-increment: h4;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) ". "
}

h5:before {
    counter-increment: h5;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5)
}

h6:before {
    counter-increment: h6;
        content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) ". "
}
```

![image](https://user-images.githubusercontent.com/3725760/47964201-0f743380-e071-11e8-9cb7-42b3554a9a55.png)
