### ISSUE TITLE
How can I resize the width of left outline panel?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#201]

**Comment by abnerlee** [comment]
Currently the only way is to change CSS.

For resize sidebar by drag & drop, see #116

**Comment by leewi9** [comment]
I'm sorry but how I change the width in CSS? There seems not an outline panel when I export to html with style.

**Comment by abnerlee** [comment]
```css
#outline-dropmenu {
  width:300px;
}

.typora-node.pin-outline #write {
    left: 300px;
}
```

Maybe not well named and not convenient. So #166 would be supported in future
