### ISSUE TITLE
How to adjust the color of highlight?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#204]
Default color for highlight (==text==) is yellow, how can I adjust to other colors?

**Comment by abnerlee** [comment]
highlight is render by `<mark>` tag, so you could add CSS:

```css
mark {
 background-color: red;
}
```

About where to put this css snip, please refer <http://support.typora.io/Add-Custom-CSS/>
