### ISSUE TITLE
How to change the width and height of sag rendered by MathJax?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#205]
the default sag is too small for me, and I want to customise its width and height, how can I do this, I've tried to add the following css but seems not working:
```css
svg {
    width: auto !important;
    height: auto !important;
}
```

regards,
