### ISSUE TITLE
How to change the width and height of svg rendered by MathJax?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#206]
![2016-06-29 17 14 11](https://cloud.githubusercontent.com/assets/10832544/16447005/ecb97916-3e1c-11e6-856c-6c6de35a73df.png)

the default svg is too small for me, and I want to customise its width and height, how can I do this, I've tried to add the following css but seems not working:

``` css
svg {
    width: auto !important;
    height: auto !important;
}
```

regards,
