### ISSUE TITLE
Gothic theme has zero margins on export

### ISSUE THREAD

**Issue by k-bx** [typora/typora-issues#2148]
I love the Gothic theme, and I've used it for [my blog](https://k-bx.github.io/). The problem with it is that, when you export to HTML, and open it via mobile, you would see zero-margin on your content, which makes it look not very nice. I've fixed this by appending a crude:

```css
body.typora-export {	
	padding-left: 20px !important;
	padding-right: 20px !important;
}
```

but I suspect something less hardcore can be done. Would love to see this spread in Typora update instead of fixing this on all my computers.

Thank you!
