### ISSUE TITLE
"Control TOC Levels" how-to is wrong

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#223]
The [Control TOC Levels](http://support.typora.io/TOC-levels/) How-to page says that "to hide low level headings, for instance, h6, you would append css:"

```CSS
h6 {
  display: none;
}
```

But it should be:

```CSS
.md-toc-h6 {
  display: none;
}
```
