### ISSUE TITLE
Font style doesn't render on Ubuntu

### ISSUE THREAD

**Issue by sourcerunner** [typora/typora-issues#2268]
1. I found that some font styles aren't displayed correctly. Here is the test:
    Not work: **bold, Italy**
    Work well: **underline, delete line, code**
2. I found that some with some themes I can escape from this issue:
    themes that renders well:  **night, whitey**
    that have this bug: **github, newsprint, pixyll**
3. Ubuntu version: 18.10
    typora version: 0.9.66

**Comment by StefanTT** [comment]
I have the same issue on ArchLinux with Gnome.
Installing Open Sans (via package ttf-opensans) did not fix the problem.

After some trial and error I found out that on my system the font is named "Open Sans Regular" and not "Open Sans"

Changing the body block in Typora's github.css fixed it for me:
```css
body {
    font-family: "Open Sans Regular","Open Sans","Clear Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
    color: rgb(51, 51, 51);
    line-height: 1.6;
}
```
