### ISSUE TITLE
Change checkbox symbols in Newsprint theme from ✔️ to normal checkbox ✅ 

### ISSUE THREAD

**Issue by AlienKevin** [typora/typora-issues#2450]
# Problems
The checkbox in newsprint theme is a thin gray checkmark. **It's hard to distinguish the checkmark in the already gray background**.
This is how checkboxes look currently:

![image](https://user-images.githubusercontent.com/22850071/56864848-55151780-6995-11e9-823c-b972f6c8d6b4.png)

# Solution
I think newsprint theme should **revert back to the original checkbox** which stands out and fits well with the gray background and provides a more consistent and familiar user experience.
I currently add the following lines to my `base.user.css` to solve the problem:
```css
.md-task-list-item > input {
    margin-top: calc(1rem - 10px); /* raise the checkbox 2px higher towards middle of line */
}

.md-task-list-item > input::before{
    content: none; /* remove the thin checkmark and revert back to original checkbox */
}
```
This is how checkboxes look after modification:

![image](https://user-images.githubusercontent.com/22850071/56864818-01a2c980-6995-11e9-870c-201eb0f18e83.png)
