### ISSUE TITLE
[BUG?!] In HTML exported by Windows and MacOS, the CSS output from the same style will be different?

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#2896]
There is such a style in my theme CSS:
```css
.mdx-background-blurs {
  backdrop-filter: blur(15px);
  -webkit-backdrop-filter: blur(15px);
}
```

Exported to HTML in macOS, can be loaded with this style, but exported to HTML in windows, the content of this style is empty:
```css
.mdx-background-blurs {
}
```
