### ISSUE TITLE
Displays custom internal anchors as inline-html

### ISSUE THREAD

**Issue by flamewave000** [typora/typora-issues#2921]
If you wish to place your own anchors within a document, the proper way to do it with MarkDown is as follows:

```html
<a name="my-anchor-name></a>
```

This allows you to then reference that anchor with `[text](#my-anchor-name)`. This functionally works in Typora as it is standard MD, but the issue I have is in how the anchor is displayed. Currently it is recognized as just plain inline html, and unlike `<br/>` or `<p>` tags, will always be shown in the displayed text. This is really annoying as it will cause issues with formatting, especially inside of table cells.

It would be very nice if `<a>` tags could be recognized and collapsed similar to how other tags are handled in Typora. Maybe even replaced with a small anchor icon like `⚓&#9875;`, until hovered on, in which case it would reveal either the raw html, or a little editor window similar to other components in Typora (ie. Table, TOC)

**Comment by DutchPete** [comment]
Yes !!! I fully support this. I use anchors a lot and hope that this request can be fulfilled.

**Comment by abnerlee** [comment]
We do not have plans to include too much "view" preferences to define how each block / styles looks like.

So, for this, you could use custom CSS to specify how hyperlink looks.
```css
/* hide the anchor HTML */
a[name]:empty + .md-raw-inline {
  display:none;
}
a[name]:empty {
  text-decoration: none;
}
a[name]:empty:before {
 content:"⚓";
}
/* show the anchor HTML when cursor is inside */
.md-expand .md-raw-inline {
    display: inline !important;
}
```

**Comment by DutchPete** [comment]
@abnerlee : many thanks for that, it works like a charm.

**Comment by flamewave000** [comment]
Awesome! I already a modified version of the Night theme that I'll add this to as soon as I get on my computer. Thanks so much!

It would be great to maybe have a sort of tips and tricks section of the theme docs to provide these kinds of CSS snippits. That way there could be some "commonly used" stylesheets that people can grab and modify for their custom themes.

**Comment by SnailDove** [comment]
The better one than above those without css settings:
```html
<span name="id">Target here</span>
[Go to Target](#id)
```
@flamewave000 @DutchPete @abnerlee

**Comment by DutchPete** [comment]
@SnailDove : you misunderstand. @flamewave000's original comment shows the anchor code is already known, and it works. The CSS code is to have an anchor icon to show where the anchor is when you are in Read mode and cannot see the raw code.

**Comment by SnailDove** [comment]
> @SnailDove : you misunderstand. @flamewave000's original comment shows the anchor code is already known, and it works. The CSS code is to have an anchor icon to show where the anchor is when you are in Read mode and cannot see the raw code.

Thanks for your tip @DutchPete

**Comment by DutchPete** [comment]
@SnailDove : you're welcome ;-)
I think this issue can be reclosed, do you agree?

**Comment by vassudanagunta** [comment]
@flamewave000 @DutchPete check out #1317, which I updated with this issue as another it would solve beautifully and easily: users would not have to customize CSS, much less customize CSS for every tag you want with this behavior.

**Comment by DutchPete** [comment]
@vassudanagunta : thanks for this tip. I looked through that very extensive issue #1317 and I must admit, with not a little bit of shame, that I do not understand the point you are making.
Although I sounds pretty obvious what is meant by `Display source for simple block on focus`, I don't get it. I probably have too basic a knowledge of Markdown and/or Typora to be able to grasp what you are driving at. I regularly switch to Source Code Mode to fix the appearance of things in WYSIWYG mode/Read Mode, but that does not bother me.

What I can say is that I don't mind making adjustments to the `base.user.css` file, that is what it is there for, after all. I am personally very happy with Typora overall. The issues I have are:

* the rendering of footnotes: I find it very inconvenient that one cannot click on a number to get to them AND click on a little return arrow to get back to the right point in the text. Furthermore, I miss the possibility of inline footnotes.
* Right now one has to choose between File Tree and Outline in the left hand panel, I would like to have an extra panel.

Having said that, I live with this as is, and since @abnerlee has more than enough issues on his plate I will not add more.

**Comment by vassudanagunta** [comment]
@DutchPete 

The `/* show the anchor HTML when cursor is inside */` part in the custom CSS above does exactly what I'm suggesting by `Display source for simple block on focus`, except that **it should be a first class part of the UX**, not something only technically adept people can do. It also should apply to all non-display inline HTML, e.g. HTML comments, div tags, #1026, etc. 

If done right, switching to source code mode would not be something you need to do "regularly". What makes Typora loved by so many is that it is WYSIWYG, but it falls short of this goal in many ways (see #2485).

Your point about footnote rendering is actually a perfect example of this. What you describe is what a truly WYSIWYG editor would do. It takes what I suggest for footnotes in #1317 one step further and provides the better solution to #319 than @abnerlee chose. 

I agree, @abnerlee has a lot on his plate. I hate it when people make entitled demands, especially given that they are using Typora for free. But I think that for any product developer thoughtful user feedback is gold!

**Comment by DutchPete** [comment]
@vassudanagunta : I too love Typora for its WYSIWYG side, I hate markdown editors with an edit and a preview pane sharing my screen.

> But I think that for any product developer thoughtful user feedback is gold!

Absolutely, and what you are doing is very useful and must be of great help to @abnerlee. Nevertheless, I will stay out this discussion because I am not sufficiently technically savvy to be able to make a useful contribution.

**Comment by RealTrisT** [comment]
> We do not have plans to include too much "view" preferences to define how each block / styles looks like.
> 
> So, for this, you could use custom CSS to specify how hyperlink looks.
> 
> ```css
> /* hide the anchor HTML */
> a[name]:empty + .md-raw-inline {
>   display:none;
> }
> a[name]:empty {
>   text-decoration: none;
> }
> a[name]:empty:before {
>  content:"⚓";
> }
> /* show the anchor HTML when cursor is inside */
> .md-expand .md-raw-inline {
>     display: inline !important;
> }
> ```
> 
> Hope that helps :)

@abnerlee this is no longer working, and the [documentation here](https://support.typora.io/Links/) also still has this wrong CSS.

I made this real quick but my css skills aren't the best:

```css
span.md-html-inline .md-raw-inline {
	display: none;
}

span.md-html-inline.md-expand .md-raw-inline {
	display: inline !important;
}

span.md-html-inline a:before {
	content: "";
}

span.md-html-inline a:empty:before {
	content: "⚓";
}
span.md-html-inline.md-expand a:empty:before {
	content: "";
}
```

If it gets put in `base.user.css` it works and the icon doesn't show up when you export. I only somewhat understand why this isn't default behavior (the "what you see is what you get" philosophy and all that), but you guys should at least make it a preferences setting, because this is particularly useful. Also, make it more clear in that page where it is the code should be put because it took me 20 minutes to find out about base.user.css and I was just editing theme files directly.

![fj8ayoWni7](https://user-images.githubusercontent.com/30376152/162370591-011318d4-0f3c-4902-820d-774ba1ec1b65.gif)

Hope it helps.

**Comment by 2-3-5-7** [comment]
@RealTrisT  you need to change `a[name]` to `a` if you anchors don't have a name attribute, but I also think that [the document](https://support.typora.io/Links/#internal-links) needs to be updated. @abnerlee 
```css
/* hide the anchor HTML */
a:empty + .md-raw-inline {
  display:none;
}
a:empty {
  text-decoration: none;
}
a:empty:before {
 content:"⚓";
}
/* show the anchor HTML when cursor is inside */
.md-expand .md-raw-inline {
    display: inline !important;
}
```
