### ISSUE TITLE
Page-break-before not working on h1 upon PDF export

### ISSUE THREAD

**Issue by noahboegli** [typora/typora-issues#2979]
Hi!
I have a custom css for when I export in PDF:
```css
@media print {
  h1 {
    page-break-before: always;
  }
  h2 {
    page-break-before: always;
  }
}
```
But as you can see on the following picture, it does not work...
***
![Capture](https://user-images.githubusercontent.com/39568628/68035424-dee6ca00-fcc3-11e9-89bc-6d574a74a9db.PNG)
***
I have been trying to find a solution to that issue all day but I have not been able to succeed.

If I export in HTML and then in print the exported HTML, it works. Exactly as mentionned in this issue: https://github.com/typora/typora-issues/issues/2953

Thank you!
