### ISSUE TITLE
Does Typroa not support `@media (prefers-color-scheme: dark)`?

### ISSUE THREAD

**Issue by MadMaxChow** [typora/typora-issues#3000]
My CSS is like this, and the system chooses Dark Mode, but it doesn't respond when Typora chooses the theme of this style setting (the background doesn't turn black), which is normal in the browser.

```CSS
:root {
    --bg-color: #FFF;
}

@media (prefers-color-scheme: dark) {
    :root {
        --bg-color: #000;
    }
}

body {
    background-color: var(--bg-color);
}
```
