### ISSUE TITLE
table display issues when paginating, in pdf

### ISSUE THREAD

**Issue by lk-nick** [typora/typora-issues#3418]
- current version: 0.9.86
- theme: dorpbox, github, etc.

I have added the following custom css, but it didn't work.

``` css
@media print {
  table {
   page-break-inside: auto;
  }
}
```

display like this

![typero-table-issues](https://user-images.githubusercontent.com/4994965/78748097-b020fe00-799d-11ea-8d92-a13d356132cb.png)

**For version 0.9.70, this is ok. Like this**

![typora-table-right](https://user-images.githubusercontent.com/4994965/78748482-bd8ab800-799e-11ea-9554-b1de010c4e4f.png)
