### ISSUE TITLE
how can i change math foluma font-size?

### ISSUE THREAD

**Issue by zcrbb** [typora/typora-issues#3475]
Version: 0.9.86

i use night theme.
![image](https://user-images.githubusercontent.com/40193711/81034901-4841d280-8ecb-11ea-81db-a4dcf57e6b4f.png)
font is too small for me....

how can i change math foluma font-size? 
it seems like settings not in night.css file.

**Comment by abnerlee** [comment]
You can add following CSS
```css
.MathJax_SVG {
font-size: 110% !important;
}
```
