### ISSUE TITLE
Extend typora typing space

### ISSUE THREAD

**Issue by mHatsune** [typora/typora-issues#3684]
![image](https://user-images.githubusercontent.com/63988538/87216481-26594600-c37b-11ea-9d19-b9182b0e2737.png)
@abnerlee

**Comment by Shen897** [comment]
I'm not a CSS expert but I increased it by increasing the value of max-width

```css
#write {
    max-width: 1200px; /* increase the value of max-width*/
}
```
