### ISSUE TITLE
Mermaid Cylinder Node not rendering correctly

### ISSUE THREAD

**Issue by MishaVeldhoen** [typora/typora-issues#3703]
**Typora version:** 0.9.92 beta
**Platform:** Windows
**Problem:** When rendering a mermaid graph, the cylinder node renders completely black.

![typora_diagram_test](https://user-images.githubusercontent.com/2463292/87406214-b4723e00-c5c0-11ea-8403-f0c7ef0015d7.PNG)

**Comment by abnerlee** [comment]
@MishaVeldhoen would you paste the mermaid content for us to test?

**Comment by MishaVeldhoen** [comment]
The code to reproduce is simply:
```
graph LR
  id[(test)]
```

**Comment by pchesneau** [comment]
Quick workaround that i'm using : 
In `%APPDATA%/Roaming\Typora\themes`
add a file named `base.user.css` with the following content: 
````css
.node path {
  fill: var(--node-fill);
  stroke: #9370DB;
  stroke-width: 1px; }
````
Hope it helps!
