### ISSUE TITLE
Cursor forces hard left on mouse click of first line only - Win10 version 0.9.92

### ISSUE THREAD

**Issue by narration-sd** [typora/typora-issues#3718]
[think I posted this at first in wrong repo; copied here so you can be sure to see it, and the compliment, Abner]

I believe began on this release

- new document
- type a first line
- click mouse anywhere within line
- cursor jumps back to beginning of this first line
- only arrow keys can move cursor now on that first line
- give up, arrow to end of line, return key to start another
- on second line, clicking puts cursor where you clicked, in the normal way
- any further lines, still works
- first line, never
- now, go to that beginning of first line and insert (type) a # - Markdown top title
- click another line, first now has style
- click within first line once again: line reverts to plain text, but cursor is where you clicked
- but try clicking again, and now you are back to forced to beginning of line

I think that story about covers it.  

Then I have to say, Typora is wonderful - have used it for years as a primary Markdown editor, 
and as literary journaling editor as well.  

Thank you, Abner.

**Comment by abnerlee** [comment]
Possible to attach a screencast about this, since we cannot reproduce it.

**Comment by abnerlee** [comment]
relates #3696

**Comment by narration-sd** [comment]
![sticking-first-line-cursor](https://user-images.githubusercontent.com/247945/88079334-69ad7480-cb32-11ea-91f6-4811c0d83e94.gif)

Here's a gif movie which shouild illustrate fully, Abner, thanks...

**Comment by narration-sd** [comment]
Abner, two more points to help:
- I tried closing Typora and re-opening, choosing the file. The same force-left-on-click behavior showed on the first line, with no additional typing
- I then fully removed Typora 0.9.92 from the machine (very up-to-date and maintained Win10 Home; I develop software), and installed instead 0.9.89 from the list you kindly provided. On 0.9.89, there is no problem. The cursor goes where you click the mouse, everywhere including the first line.

Should help, I think...best, Clive

**Comment by cchdequip** [comment]
Just to let you know that this problem continues unchanged, in latest 0.9.93
I've sent you the movie requested of this happening in detail, above
I've again reverted to 0.9.89 to write without the issue

**Comment by narration-sd** [comment]
@abnerlee  - just noticed the Need More Info label still on this -- two weeks ago, I gave you the info you wanted, a movie -and more - few items above if you want to visit this issue....

Thanks, Clive

**Comment by abnerlee** [comment]
@narration-sd Sorry for late reply. I saw your videos but still unable to reproduce this on my own, so:

- Which theme did you use and does this happen in built-in themes?
- By click, you mean mouse click or just click using trackpad, or there's no difference.
- Did you use any IME or non En-US keyboard layout to input the first sentence?

**Comment by narration-sd** [comment]
@abnerlee  great, think your ideas found it...
- I was using Ursine Umbra -- kind of a very nice and friendly one, reminds of childhood even though I am 'mature'; good atmosphere for attitude in fiction writing
- and indeed, the problem is there, in Ursine Umbra, maybe others, but not in all Themes. 
- I tried Minimalism and Night just now, and no problem occurs - they are fine on this issue
- I went back to Ursine Umbra, and the problem recurs, so that's pretty solid
- I'm exclusively using the trackpad on the laptop
- no IMEs turned on, though I have a Korean one (!) available - once lived there, taught grad school design, very fine & interesting times, and part of a life there in my 20s

Ok, enough history, and hope this gets you on a straightforward track, Abner.

I really value Typora, use it for fiction as said, journaling, and also some other things, or checking a result.
It's really a fine tool to work with, in all ways.

Best,
Clive

**Comment by narration-sd** [comment]
@abnerlee  just so you know...^^^

**Comment by abnerlee** [comment]
For hot fix you can change
```css

#write > p:first-child:not(:only-child)::before, 
#write > p:only-child::before {
  content: '';
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: url("ursine/night.png") no-repeat 45% 90% transparent;
  background-size: cover;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  opacity: 0;
}

#write > p:only-child:empty::before {
  opacity: 1;
}
```

to


```css
#write > p:only-child:empty::before {
  content: '';
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: url("ursine/night.png") no-repeat 45% 90% transparent;
  background-size: cover;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  opacity: 1;
}
```

in ursine-umbra.css
