### ISSUE TITLE
Non-interactive checkbox in exported HTML

### ISSUE THREAD

**Issue by yerumaku** [typora/typora-issues#3750]
Can I get **not disabled** `checkbox` when printing in HTML? 
I use them in the my css theme to collapse lists.
### Theme
```css
ul > li.task-list-not-done:first-child ~ li {
  display: block;
}
ul > li.task-list-done:first-child ~ li {
  display: none;
}
```

### Typora
```md
- [x] collapsed
- hidden text
- hidden text too
```
![Typora](https://user-images.githubusercontent.com/21119896/88952823-a00c9180-d2a0-11ea-98af-0e901f48b5ea.png) ![Typora](https://user-images.githubusercontent.com/21119896/88952874-b7e41580-d2a0-11ea-9edd-33ebbe424d34.png)

### HTML
```html
<li class="md-task-list-item task-list-item task-list-done">
  <input type="checkbox" disabled="disabled" checked="">
  <p><span>collapsed</span></p>
</li>
```
![image](https://user-images.githubusercontent.com/21119896/88952975-e7931d80-d2a0-11ea-9f1a-6c8761d58d0a.png)

### PDF
```css
@media print {
  ul > li.task-list-not-done:first-child ~ li {
    display: block;
  }
}
```
`@media print` work in PDF, but it doesn't work for export to HTML.
![image](https://user-images.githubusercontent.com/21119896/88953949-4dcc7000-d2a2-11ea-9bf0-c1464f99a48b.png)
