### ISSUE TITLE
Cannot Highlight Text or Move Cursor with Mouse

### ISSUE THREAD

**Issue by rhysdotink** [typora/typora-issues#3868]
### System Information
**Operating System:** Windows 10
**Typora Version:** 0.9.96

 ### Issue
Hello,

I am having an issue wherein I cannot select text by clicking and dragging my cursor. This is a new issue that I've only just encountered recently.

When opening old files that I have been working on for a while, I can highlight text just fine. However when I open a new file or open a file that I created after encountering this issue for the first time, I cannot select/highlight any text using my mouse.

Attempting to select text using the mouse results in the cursor jumping from its current place in the text back to the beginning of the block/paragraph.

The same happens when attempting to move the cursor to a new place in the paragraph. Clicking anywhere within the paragraph will not place the cursor where I clicked, but at the beginning of the paragraph.

This issue only occurs outside of the View Source Code mode. When View Source Code is active, the mouse can be used to move the cursor and highlight text as normal. However, the issue returns when View Source Code is disabled.

Thus far the issue has persisted through restarting the program, switching between the "classic" and "unibody" appearances, restarting my computer, and restarting my mouse drivers. Typora is the only program that this occurs in.

Selecting text and moving the cursor is still possible using the keyboard.

This issue persists regardless of whether Focus and/or Typewriter Mode are enabled or disabled.

I do not know how to replicate this issue as I do not know what is causing it. It just started suddenly when I opened a new file.

A solution or fix is greatly appreciated.

Thanks you!

**Comment by rhysdotink** [comment]
[09-22-2020-typora-log.txt](https://github.com/typora/typora-issues/files/5268646/09-22-2020-typora-log.txt)

I figured out how to find the error log/debug file, so here are my logs from all day yesterday and this morning. I figure it might be helpful. You can see where I noticed the error because I started opening, closing, etc. Typora trying to get it to work again.

**Comment by abnerlee** [comment]
How to reproduce this? Possible to send us <hi@typora.io> a screencast about this?

**Comment by abnerlee** [comment]
> I've just figured out that the issue was caused by the theme UrsineUmbra (and Polar as well)

I see, I'm closing this.

**Comment by bran112299** [comment]
Hi, I would like to know what part of a theme causes this issue to happen, I have it on every other note.

**Comment by bran112299** [comment]
> Hi, I would like to know what part of a theme causes this issue to happen, I have it on every other note.

Upon further analysis of css its an error with adding a splashscreen.
The theme I was using that caused this is:
```css
#write>p:first-child:not(:only-child)::before,
#write>p:only-child::before {
    background: url("cobalt/splash.png") no-repeat 45% 90% transparent;
    background-size: cover;
    bottom: 0;
    content: '';
    display: block;
    height: 100%;
    left: 0;
    max-width: 100%;
    opacity: 0;
    position: absolute;
    right: 0;
    top: 0;
    width: 100%;
}
```
