### ISSUE TITLE
How to change the font style and size on the left panel?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#391]
![image](https://cloud.githubusercontent.com/assets/10832544/19834928/c801bea0-9eaf-11e6-91d5-a94f9659b34c.png)

tried this the `width` is working but the `font-size` not work:

```
#outline-dropmenu {
  width: 500px !important;
  font-size: 26px !important;
}
```

**Comment by abnerlee** [comment]
```css
.typora-node #outline-content
{
  font-size: 26px
}
```
