### ISSUE TITLE
toc style

### ISSUE THREAD

**Issue by cyysu** [typora/typora-issues#4143]
hello，The style of my TOC is as follows

![image](https://user-images.githubusercontent.com/10364320/106264858-2c543d00-6261-11eb-8ffe-11926234e450.png)

But when I click the mouse, the font of the directory will be displayed
![image](https://user-images.githubusercontent.com/10364320/106265007-64f41680-6261-11eb-8acb-8c357c51cb38.png)

How can I set the CSS so that it will show the same effect as the second image, which shows the words of the directory, without a mouse click？

Thanks

**Comment by abnerlee** [comment]
```css
.md-toc-content {
    border: dashed 1px #999;
    border-color: var(--panel-border-color);
    margin: 19px -1px;
    margin-top: -1px;
}
#write div.md-toc-tooltip {
 display:block !important;
}
```

You could see "debug css" part in https://support.typora.io/Add-Custom-CSS/
