### ISSUE TITLE
Table of contents overflow

### ISSUE THREAD

**Issue by gruvw** [typora/typora-issues#4201]
### Issue

The following heading will not induce a proper line break (with most if not all themes) and is therefore overflowing from the table of contents.

### Steps to reproduce

```markdown
[TOC]

# tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt
```
(you might have to input more t(s))

### Solutions

I can see two possible solutions right now:

1. Wrap anywhere:
```css
.md-toc-content a {
  overflow-wrap: anywhere;
}
```

2. Scroll:
```css
.md-toc-content {
  overflow: scroll;
}
```
