### ISSUE TITLE
Images with CSS box-shadow attribute are not rendered properly

### ISSUE THREAD

**Issue by xiaotianxt** [typora/typora-issues#4347]
## Environment Info
System Version: MacOS 11.2.3
Typora Version: 0.10.6 (5297)

## How to reproduce
I'm using customized CSS code:
```css
img {
  border-radius: 10px;
  box-shadow: 3px 3px 15px rgba(0, 0, 0, 0.5);
  -moz-box-shadow: 3px 3px 15px rgba(0, 0, 0, 0.5);
  -webkit-box-shadow: 3px 3px 15px rgba(0, 0, 0, 0.5);
}
```
to make additional shadow effect, but typora cannot render it properly.

## Bug detail
Here is what it looks like in typora:
![image](https://user-images.githubusercontent.com/17041194/116434352-ecf7b580-a87c-11eb-8df4-e56514f0cc57.png)
Noticed that there are some blank space between image and border, but I didn't set any border. 

Also if I export the `.md` file into `.html` with style, it can be rendered by chrome properly:
![image](https://user-images.githubusercontent.com/17041194/116434613-24666200-a87d-11eb-807e-cd44aa53d504.png)

I do believe there's something wrong with typora.
