### ISSUE TITLE
Mermaid options not work

### ISSUE THREAD

**Issue by sinomoe** [typora/typora-issues#4384]
typora version: 0.10.9(5330)
OS version: macOS 11.2.3

Following the instuctrions on [flowchart curve](https://support.typora.io/Draw-Diagrams-With-Markdown/#flowchart-curve) and [Custom CSS](https://support.typora.io/Add-Custom-CSS/), I add the css below into `base.user.css`

```css
:root {
	–-mermaid-flowchart-curve: basis; /*not work*/
	--sequence-theme: hand; /*it works*/
}
```

The result is that the first line not work and second line works, I run typora 0.10.9(5330) on macOS 11.2.3, Thx for your helps!
