### ISSUE TITLE
List Alignment

### ISSUE THREAD

**Issue by AhmedThahir** [typora/typora-issues#4786]
There is a weird bug with ordered(numbered) list in MacOS.

## Unordered List in Windows/MacOS
![Screen Shot 2021-11-07 at 7 01 14 PM](https://user-images.githubusercontent.com/26618217/140650411-df3f0566-62a7-4327-85a2-75425e8c9724.png)

## Ordered List in Windows
![image](https://user-images.githubusercontent.com/26618217/140650595-99a1a9be-4e64-478a-bc77-8f77f77734ff.png)

## Ordered List in MacOS
![Screen Shot 2021-11-07 at 7 00 07 PM](https://user-images.githubusercontent.com/26618217/140650356-461bfa98-d9bb-4e5d-a502-533471ff4302.png)

If you see, despite using the same settings in Windows and MacOS:
``` css
#write ul, #write ol {
padding-left: 2ex !important;
margin-top: 0 !important;
}
```

the number in macos is aligned weridly - it is wayyy more to the left, **even though it's the same settings**.
