### ISSUE TITLE
[Feature] `data-alt` to be included in parent span of images along side `data-src`

### ISSUE THREAD

**Issue by strawp** [typora/typora-issues#4874]
I'm creating a theme where I want to have a caption below each image taken directly from the markdown, using the alt part of the tag as the caption. I can do this as follows:

```css
span[md-inline=image]::after{
  counter-increment: figurenum;
  content: "Figure " counter(figurenum) ": " attr(data-alt);
  font-size: 80%;
  display: block;
  text-align: center;
}
```

Which works really nicely, giving me automatically incrementing figure numbers and simple captioning, however `data-alt` doesn't exist on the relevant element:

![image](https://user-images.githubusercontent.com/548565/144412679-8b548472-a7a2-4958-b52a-f17b8be3adbf.png)

Can this be added in so that styles like the above work?
