### ISSUE TITLE
footer isnt full window width when window >1270px

### ISSUE THREAD

**Issue by KrayZeee** [typora/typora-issues#4920]
footer isnt full window width if the window is greater then 1270px

![Screenshot 2021-12-12 171751](https://user-images.githubusercontent.com/5563915/145720491-40520696-3b89-4743-9613-6f399497e4de.png)

can be fixed by setting in window.css the right property to 0px 
```css
@media (min-width:1270px){.pin-outline footer.ty-footer{background-color:transparent;border-top:0!important;right:0px}
```

Windows 10 64bit
version 1.0.3
