### ISSUE TITLE
Font size issue when editing Headers

### ISSUE THREAD

**Issue by RenaudDenis** [typora/typora-issues#4957]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**

There is a styling issue whenever a header is edited.
Headers loose their styling and seem to be reset to stuff like _left align_, _smaller font size_, _smaller padding_, etc.

**To Reproduce**

Just take any theme in the 1.0.5 version of Typora

**Expected behavior**

I expect as few styling changes as possible, as with pre-1.0 versions

**Screenshots / Screencasts**

![Screen Recording 2021-12-27 at 15 27 19](https://user-images.githubusercontent.com/2025489/147481793-acfb6f74-ca58-4f25-8cef-dfe6e4409b2d.gif)

**Sample Markdown File**

[Untitled.md](https://github.com/typora/typora-issues/files/7780596/Untitled.md)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.1

**Typora Version**

1.0.5 (licensed version)

**Additional context**

None

**Comment by abnerlee** [comment]
Please try disable "Display source for simple blocks (including headings, etc.) on focus" in Preferences Panel -> Editor -> Live Rendering as a work around.

**Comment by Thysrael** [comment]
I checked the DOM while editing a heading in Typora's GitHub theme.
Typora turns the focusing edit state of headings into a paragraph-like block such as:

```html
<p class="md-end-block md-p md-focus" mdlike="h2">
  <span class="md-block-like">
    <span class="md-blockmeta">## </span>
    <span class="md-header-span">
      <span class="md-plain md-expand">Heading text</span>
    </span>
  </span>
</p>
```

So a CSS workaround is to stylep `.md-p[mdlike="hN"]` to match the rendered heading typography, and make the inner editing spans inherit the heading font styles.

I use this patch to `github.css`:

```css
/* Keep source-view heading paragraphs visually aligned with rendered headings. */
#write > p.md-p[mdlike^="h"] {
    margin-top: 1rem;
    margin-bottom: 1rem;
    font-weight: bold;
    cursor: text;
}

#write > p.md-p[mdlike="h1"] {
    font-size: 2.25em !important;
    line-height: 1.2 !important;
    border-bottom: 1px solid #eee;
}

#write > p.md-p[mdlike="h2"] {
    font-size: 1.75em !important;
    line-height: 1.225 !important;
    border-bottom: 1px solid #eee;
}

#write > p.md-p[mdlike="h3"] {
    font-size: 1.5em !important;
    line-height: 1.43 !important;
}

#write > p.md-p[mdlike="h4"] {
    font-size: 1.25em !important;
}

#write > p.md-p[mdlike="h5"] {
    font-size: 1em !important;
}

#write > p.md-p[mdlike="h6"] {
    font-size: 1em !important;
    color: #777;
}

#write > p.md-p[mdlike^="h"] :is(.md-block-like, .md-header-span, .md-header-span .md-plain) {
    font: inherit !important;
    color: inherit !important;
}

#write > p.md-p[mdlike^="h"] .md-blockmeta {
    color: #8c8c8c !important;
}
```
