### ISSUE TITLE
Checkbox color and marker

### ISSUE THREAD

**Issue by ProStatFFM** [typora/typora-issues#5013]
Dear Typora user,

I'm working since hours on such a little problem: how to change the color when checking a checkbox. So what have I done:

1. I copied the Github theme and used it as my own. I have adapted several things on my own successfully.
2. I localized the Task List option in css:

.md-task-list-item > input {
  margin-left: -1.3em;
}

I tried several thing like "color" or "background-color" but there is still the blue color when marking a checkbox. I also tried changing base.css in my default Typora folder, but even when changing entries for checkboxes, it doesn't change the blue color.

What I want is the css code for changing the box color (from blue to any color) when marking a checkbox and - if possible - changing the default mark icon color (it's white at the moment).
<img width="69" alt="Screenshot 2022-01-19 164146" src="https://user-images.githubusercontent.com/98039393/150164660-71348804-f817-4548-a022-cd36e34a91a2.png">
Thank you
Nick

**Comment by abnerlee** [comment]
Github uses default checkbox style, so there's no one-line code to change it.

It is CSS, you could refer https://www.w3schools.com/howto/howto_css_custom_checkbox.asp and debug in Typora following https://support.typora.io/Add-Custom-CSS/#debug-css

For example:

```css
.md-task-list-item>input {
margin-left: -24px;
margin-top: calc(1rem - 11px);
-webkit-appearance: none;
background-color: #2196F3;
width: 16px;
height: 16px;
border-radius: 2px;
}

.md-task-list-item > input:before {
content: ' ';
font-family: Arial;
display: inline-block;
width: 16px;
height: 16px;
vertical-align: middle;
text-align: center;
color: #ddd;
left: 4px;
top: 2px;
width: 7px;
height: 12px;
border: solid white;
border-width: 0 3px 3px 0;
-webkit-transform: rotate(45deg);
-ms-transform: rotate(45deg);
transform: rotate(45deg);
position: absolute;
}

.task-list-not-done > input:before {
  border: none;
}
```
