### ISSUE TITLE
Z-index CSS behaviour doesn't match toolkit / general CSS

### ISSUE THREAD

**Issue by TEParsons** [typora/typora-issues#5061]
- [ x] Searched existing issues to avoid creating duplicates.

- [NA ] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x ] Searched http://support.typora.io/

----

**Describe the bug**
When creating custom CSS for Typora using the [theme toolkit](https://github.com/typora/typora-theme-toolkit), I've noticed something which behaves differently in the toolkit (and in CSS in general) than in the actual software. When setting the z-index of a pseudo element to -1, it should position the pseudo element behind its parent if the parent has a set `position` value, but in Typora it remains in front.

**To Reproduce**
1. Create a CSS theme with the following code: 
```css
#write {
    position: relative;
    width: 50vw;
    background-color: white;
}
#write:after {
    position: absolute;
    left: 10rem;
    right: 10rem;
    top: 10rem;
    bottom: 10rem;
    height: 100%;
    z-index: -1;
    background-color: red;
}
```
2. View this theme via the toolkit - `#write:after` is behind the `#write div`
3. View this via Typora - `#write:after` is in front of the `#write` div

**Expected behavior**
From what I can tell, the correct behaviour is the toolkit - setting `position` on `#write` should create a new z-index context, so setting `#write:after` to have a z-index of -1 should put it behind its parent.

**Screenshots / Screencasts**
In typora:
![image](https://user-images.githubusercontent.com/25686106/153724909-68012071-2c3a-4f2e-958b-8a96054cc15f.png)
In the toolkit:
![image](https://user-images.githubusercontent.com/25686106/153724920-61ff896a-4e69-40e3-adbd-fbf0f6ded270.png)

**Sample Markdown File**
N/A

**Desktop:**
 - OS: Windows 10 64-bit

**Typora Version**
1.0.3
