### ISSUE TITLE
How to add the page number at the end of each table of contents item

### ISSUE THREAD

**Issue by Remering** [typora/typora-issues#5137]
I need a table of contents like this

![table of contents](https://th.bing.com/th/id/OIP.pXopOAoQrem-mASNF7uhkQAAAA?pid=ImgDet&rs=1)

I have already added `..............` at the end of each table of contents item by css below
```css
.md-toc-item {
  overflow-x: hidden;
  white-space: nowrap;  
}
.md-toc-item::after {
  content: "......................................................................";
}
```
But how can I add the page number ?
