### ISSUE TITLE
How to change the background color of selected text

### ISSUE THREAD

**Issue by adesh02092000** [typora/typora-issues#5266]
I'm using a custom theme (Gothic Dark), but the background color of the selected text, makes it impossible to see anything.
What CSS can I use to change it?

Note: I am not referring to the highlight background (mark tag)

**Comment by adesh02092000** [comment]
Figured it out :rocket: 
```css
*.in-text-selection,
::selection {
  background: #4a89dc;
  color: #fff;
  text-shadow: none;
}
```
Works!
