### ISSUE TITLE
[Feature] Support Tablerize similar Syntax to produce table based on YAML/JSON data

### ISSUE THREAD

**Issue by Kimi-Arthur** [typora/typora-issues#5326]
Reference Link: https://github.com/IFTTT/tablerize

Writing tables in markdown is never a pleasant experience. However, with tablerize, if we have a YAML/JSON data stored somewhere, we can automatically populate the data into a nice table.

I would suggest this syntax with `yaml,table` as the language type, so that other Markdown parser still recognize it as a valid YAML block. But anything that's capable of handling YAML data would be great.

```yaml,table
cols:
- name: authority
- name: num_orders
- name: num_targets

data:
- authority: Legal Authority
  num_orders: Annual Number of Orders
  num_targets: Estimated Number of Targets Affected
- authority: |
              __FISA Orders__  
              Based on probable cause
              (Title I and III of FISA, Sections 703 and 704 of FISA)
  num_orders: "1,167 orders"
  num_targets: "1,144"
- authority: |
              __Section 702__  
              of FISA
  num_orders: "1 order"
  num_targets: "89,138"
- authority: |
              __FISA Pen Register/Trap and Trace__  
              (Title IV of FISA)
  num_orders: "131 orders"
  num_targets: "319"
```

See the link above for desired output.
