### ISSUE TITLE
Brackets highlighting does not work

### ISSUE THREAD

**Issue by Serious54088** [typora/typora-issues#5666]
**Describe the bug**

Hi, I has a problem with the custom theme.
I want to change the color of the brackets in the code block, but their CSS modification does not work. 
The brackets still have the same color as the nomal text. Other code highlighting works fine, only the `.cm-bracket` does not work, I have tested this on serveral theme css.

```css
.cm-s-inner .cm-bracket {
  color: var(--code-yellow-color) !important;
}
```

**Desktop:** Windows 10 

**Typora Version:** 1.5.9
