### ISSUE TITLE
Github Style Alert cannot show in HTML or PDF

### ISSUE THREAD

**Issue by HoeYeungHo** [typora/typora-issues#6014]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
I know Github Style Alert did not adapt to i18n, so I followed the documentation to modify the CSS file, and all of this worked in typora, which is great! But when I export the markup to an HTML or PDF file, it has an effect on the style of Github Style Alert, but it does not have an effect on its text content.

* Effectively modifying styles

  ```css
  .md-alert.md-alert-tip {
      border-left: 4px solid rgb(31, 136, 61);
      padding: 10px 15px;
      color: var(--text-color);
      background-color: rgba(31, 136, 61, .02);
      border-radius:0px 5px 5px 0px ;
  }
  ```

* The modification of text content **only works in typora** and is ineffective in exported HTML and PDF files

  ```css
  .md-alert-text-tip .md-alert-text-container:after {
      content: "面试真题";
  }
  ```

**Screenshots / Screencasts**
![1712064125090](https://github.com/typora/typora-issues/assets/60749707/79a03aa7-be69-475c-a71f-9276ed04136b)

**Desktop (please complete the following information):**

Windows 11 64bit

**Typora Version**

Typora 1.8.10
