### ISSUE TITLE
Support github-style checkboxes

### ISSUE THREAD

**Issue by dwbruhn** [typora/typora-issues#615]
* [ ] This
* [x] would be awesome
* [ ] to have in Typora

**Comment by masonlr** [comment]
![screen shot 2017-03-29 at 3 38 54 pm](https://cloud.githubusercontent.com/assets/5828176/24438823/ebbce6d8-1495-11e7-863b-3b4b56ad5d86.png)

**Comment by masonlr** [comment]
Go to `Paragraph > Task List`

**Comment by solarce** [comment]
Sort of related, has anyone figured out how to change what character is show for the unchecked/checked box in a given theme?

I took a look at the .css files but I only see an empty character in `content: ';'`

**Comment by dwbruhn** [comment]
@masonlr Wow, thanks! Ah, I think the reason I didn't notice is that the auto-formatting is a little tricky. You can't convert an existing bulleted list to checkboxes by simply typing `[ ]` next to the bullet, but instead you have to delete the bullet first. 🤔

**Comment by masonlr** [comment]
@solarce Look into `.task-list` and `.task-list-item`. For example in `newsprint.css` a square root symbol (css `\221A`) is shown using:

```css
.task-list{
	padding-left: 1rem;
}

.task-list-item {
	padding-left: 1.5rem;
	list-style-type: none;
}

.task-list-item input:before {
	content: '\221A';
	display: inline-block;
	width: 1.25rem;
  	height: 1.6rem;
	vertical-align: middle;
	text-align: center;
	color: #ddd;
	background-color: #F3F2EE;
}

.task-list-item input:checked:before,
.task-list-item input[checked]:before{
	color: inherit;
}
```
