### ISSUE TITLE
↓ is displayed when there are two Spaces in the md file. How can I not display ↓

### ISSUE THREAD

**Issue by shiyunxiao** [typora/typora-issues#6177]
![image](https://github.com/user-attachments/assets/50ad0108-75e9-486f-9f61-9996e0c42f38)

**Comment by abnerlee** [comment]
It shows a hard break in Markdown, and there’s no option to hide it.

If you still want to hide it, you can add following css 

```css
[md-inline=linebreak]>.md-linebreak-mark:before {opacity: 0}
```

In custom CSS file, following https://support.typora.io/Add-Custom-CSS/

Best Regards
