### ISSUE TITLE
Can typora support Chinese fonts or 'otf' fonts?

### ISSUE THREAD

**Issue by rliangcn** [typora/typora-issues#6199]
Hi, I followed the instruction in [typora support for customizing font in css](https://support.typora.io/Custom-Font/).
It seems not work for me.

###  step 1.
I opened the themes folder, and created 'base.user.css' file, the contents in it is as follows:

``` css
/* latin */
@font-face {
    font-family: 'SourceHan';
    font-style: normal;
    font-weight: 400;
    src: local('SourceHan'), local('SourceHan-Medium'), url('./fonts/SourceHanSerifSC-Medium.otf') format('otf');
  }
  
  /* latin */
  @font-face {
    font-family: 'SourceHan';
    font-style: normal;
    font-weight: 700;
    src: local('SourceHan Bold'), local('SourceHan-Bold'), url('./fonts/SourceHanSerifSC-Bold.otf') format('otf');
  }
  
  body {
    font-family: 'SourceHan', sans-serif;
  }
```
![image](https://github.com/user-attachments/assets/746f5043-da6d-44cf-a0d0-510f55a32471)

### step 2.
I created the 'fonts' folder inside 'themes' and copied the SourceHanSerifSC-Medium.otf file for debugging.
![image](https://github.com/user-attachments/assets/7ff702b7-98d1-49b4-8221-bb2e5ce6f104)

### result
I saved the css file, restart typora, but the Chinese font seems not changed.

Am I wrong in some steps? or can typora support these sorts of fonts? Thanks
