### ISSUE TITLE
[Feature] Per-Document Control of Image Uploading and Exporting

### ISSUE THREAD

**Issue by kyouheiab** [typora/typora-issues#6301]
While I would like to use Typora as a markdown editor for the multiple service platforms, I need to change where to upload a image and export a markdown file with custom commands.

Currently, for export, we can defile the multiple profile, however we have to select the different export setting each time when I need to change the export target.
For image uploading, we can only have the single profile per Typora app, so I have to override the existing setting each time when I need to change the image uploading target.

I would propose "Per-Document Control of Image Uploading and Exporting" feature by [YAML Front Matter](https://support.typora.io/YAML/) like the following statement.

```yaml
title: My Markdown Article
typora-copy-images-to: custom commands or script to upload
typora-export-to: custom commands or script to export
```

I think this is quite feasible and useful for the people to use Typora for the multiple service platforms, thanks.
