### ISSUE TITLE
Table Border Invisible

### ISSUE THREAD

**Issue by adiamoc** [typora/typora-issues#632]
Is it possible to allow the borders of the table invisible?
Sometimes I need to have multiple pictures side-by-side or write in multiple columns, and the only possible way I found is through putting them in a table.

**Comment by abnerlee** [comment]
It is controlled by theme CSS

You could follow http://support.typora.io/Add-Custom-CSS/ and add following css

```css
#write table, 
#write th, 
#write td { border: none }
```
