### ISSUE TITLE
Base CSS width attribute overrides theme custom CSS files ...

### ISSUE THREAD

**Issue by neu-bnb** [typora/typora-issues#777]
I simply wanted to override **width** attribute of `#write` element with sth. like `width: 600px;`. But `width: initials;` property of **Base css** overrides this implementation. Commenting out this line in Base css solves the problem.

**Comment by abnerlee** [comment]
@neu-bnb on Windows or macOS?

**Comment by neu-bnb** [comment]
Windows 7 x64, 1.17.2 ia32, **C:\Program Files\Typora\resources\app\style\base-control.css**
```css
.typora-node #write{
    min-height: 100%;
    /** width: initial; */
    top: 0;
}
```
**C:\...\AppData\Roaming\Typora\themes\github.user.css**
```css
#write {
   width:         600px;
   margin-left:   100px;
}
```
